### ISSUE TITLE
Getting some python issues

### ISSUE THREAD

**Issue by riscphree** [adamflott/ircsrp2#1]
When trying to get the script working I receive this error.Messages aren't being encrypted and it's throwing that error (below). I'm using python 2.7 on debian 7, python-crypto is installed.

```
16:27:12   weechat     | python: stdout/stderr: Traceback (most recent call last):
16:27:12   weechat     | python: stdout/stderr:   File "/home/user/.weechat/python/ircsrp.py", line 1249, in
                       | ircsrp_out_msg_cb
16:27:12   weechat     | python: stdout/stderr:     msg = ircsrp_pack(ctx, msg)
16:27:12   weechat     | python: stdout/stderr:   File "/home/user/.weechat/python/ircsrp.py", line 270, in ircsrp_pack
16:27:12   weechat     | python: stdout/stderr:     ctext = ctx.cipher.encrypt(padto("M" + infos + msg, 16))
16:27:12   weechat     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'encrypt'
16:27:12   weechat =!= | python: error in function "ircsrp_out_msg_cb"
```

**Comment by adamflott** [comment]
What version of weechat?
Do you have the 'Dave' individual to auth against?
How did you start auth process?

**Comment by riscphree** [comment]
Weechat is v0.3.8. Yes, there is a dave user to auth against, and a roster file is set up. Auth is being started /ircsrp enable user pass dave. When I try to start auth with /ircsrp enable user pass dave #channel it gives the following error "Unable to locate channel; have you joined?" followed by "Error with command "ircsrp" (try /help ircsrp)"

**Comment by adamflott** [comment]
Can you try to save your server to the config so it can be addressed like:

/ircsrp enable user pass dave-nick servername.#channel

**Comment by riscphree** [comment]
that works to initate auth, but it still throws the same encryption errors

**Comment by adamflott** [comment]
Can you run this Python to see if it throws an error?

import Crypto.Cipher.Blowfish
import Crypto.Cipher.AES

a = Crypto.Cipher.AES.new("1234567890123456")

Is this error occurring with a non-Dave user?

**Comment by riscphree** [comment]
I ran that python, it did not throw any error. 

"Is this error occurring with a non-Dave user?"

Yes, it occurs with an alice user.

**Comment by adamflott** [comment]
Do you have a waiting room?

**Comment by riscphree** [comment]
If you mean a separate auth channel for Dave then I got that.

**Comment by adamflott** [comment]
Could you provide "/server raw" logs for both dave and non-dave?

**Comment by riscphree** [comment]
```
non-dave user in chat channel

14:39:14 localhost <-- | PRIVMSG #channel :test message
14:39:16 localhost <-- | PRIVMSG #channel :123456
14:39:19 localhost <-- | PING localhost
14:39:20 localhost --> | :chat.site.com PONG chat.site.com
                       | :localhost

non-dave user in auth channel
14:40:59 localhost <-- | NOTICE #auth :+srpa0 dave
14:41:01 localhost <-- | PRIVMSG #auth :testing
14:41:20 localhost <-- | PING localhost
14:41:20 localhost --> | :chat.site.com PONG chat.site.com
                       | :localhost
14:42:20 localhost <-- | PING localhost
14:42:20 localhost --> | :chat.site.com PONG chat.site.com
                       | :localhost



dave in auth channel

14:40:59 localhost --> | :alice!alice@mask-676EBE1F NOTICE #auth :+srpa0 dave
14:41:01 localhost --> | :alice!alice@mask-676EBE1F PRIVMSG #auth :testing
14:41:17 localhost <-- | PING localhost
14:41:17 localhost --> | :chat.site.com PONG chat.site.com
                       | :localhost
```

**Comment by adamflott** [comment]
Below is what a successful auth from an alice should look like

Why does your alice user have "NOTICE #auth :+srpa0 dave" ? It looks like you are sending that to the channel. When it should be a NOTICE to the dave

```
15:58:19 ircserver --> | :amf!~adam@FUR-2BF23E47.com JOIN :#waitingroom
15:58:19 ircserver --> | :irc.ircserver.net 332 amf #waitingroom :topic
15:58:19 ircserver --> | :irc.ircserver.net 353 amf @ #waitingroom :amf dave otherperson
15:58:19 ircserver --> | :irc.ircserver.net 366 amf #waitingroom :End of /NAMES list.
15:58:19 ircserver --> | :Global!serv@AC NOTICE amf :server topic. 
15:58:21 ircserver <-- | MODE #waitingroom
15:58:21 ircserver --> | :irc.ircserver.net 324 amf #waitingroom +sn 
15:58:21 ircserver --> | :irc.ircserver.net 329 amf #waitingroom 1317413562
15:58:41 ircserver <-- | NOTICE dave :+srpa0 ircsrprosteruser
15:58:43 ircserver --> | :dave!~dave@irc.example.com NOTICE amf :+srpa1 EvCTLqBb3dlZsix+xQqKw82WYAbNCKKlO2vl+MEH6m1YfJi0iY0z5I6fIFrCRa2efVt0ic1CRrVX5K5zagYQdGe2WvIApoq/cxZ4ghVwkUZ
                        | 7UnpYRW0dH3yleUDXRancNcsO42EtWRRDSA0AkdE/Kh9vS/1ff3xgQD5R53n1Gz+mdG9nVv2kzmzepsC5GpER9DHJzMsqFBKEWgv/1TnEvauh6Aqe99SF227QCecrs8VB6Ul+gpno/xH006tZzNxHrmQVJOngaQe/6yrpADY
                        | 1ARK9c/Q6AM+6kS5cyi4JiVxPk8NW9IgUvadKcQeS9OEuiovTwVPC4oS7E7/1cGi9jLP/hQPHmAK9Lf9KIsNw/m5uh6IG9qVR/FQp6vxwnEie
15:58:43 ircserver <-- | NOTICE dave :+srpa2 S4Q5SplbH8dRKnDIAA+jPKSaOLRLvsvMWmqdpjZPCUV31c+6LkGc+u0gkyoqQky/0kdAcuTA+XAj6H+IhZyfv9ppQDSsPftbGuGltiU5ptr1eowHmGuCtJH4hZd09zMQBo97kJP3qlMvNii
                        | 7AR40SSU9YoAEOB8VR+AtGv68m4HO9G3nSag41V7lhL8/aoL4r346grFuQHAIb3rg0POvr4UT56HQDtEIMC55uxP+Y7T56jK1UWEoJ/if7nPMfzlf7XEuqGAhwGY5lQX94xT/gVTu9nUD7FFbTiH/6ng7Wjktuhs2hILjDLJ
                        | CylXbr/EsTppnsnZY0EW3GJ5K/Uk12Zit1pdod59DO33TnIC2XXrGRZDhPTTfpyy7KZr7OKh8
15:58:44 ircserver --> | :dave!~dave@irc.example.com NOTICE amf :+srpa3 FXwSl6yhC0GjalqBMx96jwTzKAfXUkrOx8BjNPDtnZ9TlIsTLN2oOlcxEN5PxRu2O8obD7f+M+eDesjWoLwG9xLApgDUwsbljhGYAZt8KwW
                        | u1NB1hfaZ8IMirg2YaBXgQFKNGHSMaz2SvCyRAn1gLWerxx7qgScfwdaX2k7gesc=
15:58:47 ircserver --> | :dave!~dave@irc.example.com INVITE amf :#secretroom
15:58:47 ircserver <-- | JOIN #secretroom
15:58:47 ircserver --> | :amf!~adam@FUR-2BF23E47.com JOIN :#secretroom
```

**Comment by riscphree** [comment]
I don't know why it isn't sending the message directly to dave. I have been following the instructions on the site verbatim.

**Comment by adamflott** [comment]
I don't know why either, but I do want to resolve it. If you're willing, could I join that waiting room channel and do some debugging?

**Comment by riscphree** [comment]
Ok, sending you an email to adam@adamflott.com

**Comment by riscphree** [comment]
Let me know if/when you get a chance to take a peek.
